[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = 'Paris'

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts-ccip/=lib/ccip/contracts/', 
    '@chainlink/contracts/=lib/chainlink/contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
